### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by EliaCereda** [rjyo/libid3-ios#1]
Is it normal that when I try to compile this I get 61 warnings? Is there anything I can do?

**Comment by rjyo** [comment]
It seems fine for me. They come with the original C source.

**Comment by EliaCereda** [comment]
Thanks for answering, these are some of the warnings I get:

![alt](http://i46.tinypic.com/xnyjbn.png)

I get them by compiling with default settings, iOS SDK 5.1, both Device and Simulator (beside the warnings the library actually works).

**Comment by rjyo** [comment]
Same here... I think you can just try to use it. If it works, bingo!

**Comment by EliaCereda** [comment]
Alright, I asked because I didn't know if this was my fault...
